### ISSUE TITLE
Crystal structs instead of classes

### ISSUE THREAD

**Issue by jblindsay** [niofis/raybench#1]
Very interesting project. I would suggest changing all of the 'class' declarations in the Crystal code to 'struct' instead. This is idiomatic Crystal (https://crystal-lang.org/docs/guides/performance.html) and will increase the performance by several factors. In fact, on my machine, this (i.e. just changing the class to struct and changing nothing else) places the Crystal code that you have written at a speed very similar to Nim and C.

**Comment by niofis** [comment]
Thanks for your suggestion, I was wondering exactly the same when writing the implementation, but somewhere in the docs said that structs pass as value instead of references, and assumed the speed would be impacted. I'll make the change and upload the results soon.

Thank you again!

**Comment by jblindsay** [comment]
Glad to be of help. I think you'll find that that one small change has an enormous impact on the performance. It's because structs are allocated on the stack rather than the heap.

**Comment by niofis** [comment]
I already made and committed the changes, as you pointed out, the results
are way better. Thanks!

**Comment by asterite** [comment]
Also, don't use $globals, use CONSTANTS. In your code the globals you have, like zero, width and height, are all really constants. This should allow the compiler to do some more optimizations (though I doubt they will be significant, but using globals is not idiomatic and in fact globals will soon be removed from the language)

**Comment by asterite** [comment]
Actually, I see you use globals iside the main ray tracing loop, so I think some improvement will be visible

**Comment by niofis** [comment]
@asterite Applied the changes you suggested by using constants instead of globals, but performance was not affected. I still kept the changes because of your comment that globals might soon be removed from the language.

Results from three consecutive runs:

```
$ time ./crrb

real    2m1.602s
user    2m1.008s
sys 0m0.144s
$ time ./crrb

real    2m1.762s
user    2m1.136s
sys  0m0.180s
$ time ./crrb

real    2m2.274s
user    2m1.568s
sys  0m0.132s
```

Thanks for your input.

**Comment by asterite** [comment]
Thanks! I tried it too and didn't notice a difference, reading those globals is probably insignificant relative to the other code (or maybe LLVM is very good at optimizing this)
