### ISSUE TITLE
Should add an expected output

### ISSUE THREAD

**Issue by lostmsu** [niofis/raybench#20]
Worked on optimizing C# multi-threaded option, but the result looks like it is quite far from what I'd expect from a ray-traced image.
![csrb-mt](https://user-images.githubusercontent.com/239520/57109347-16ab8f80-6cea-11e9-8633-3086d8511a87.png)

**Comment by tilpner** [comment]
This looks like a broken/unseeded RNG to me. At least that's what caused this output a few years ago IIRC:
![image](https://user-images.githubusercontent.com/4322055/57122637-caa22e80-6d6d-11e9-9da6-bc6a1b91fee0.png)

**Comment by lostmsu** [comment]
@tilpner I fixed mine. Yeah, yours looks not entirely random either.
![csrb-mt](https://user-images.githubusercontent.com/239520/57123324-3cf71c80-6d36-11e9-9cda-5b92863dee91.png)
This one visually matches the reference C implementation.

**Comment by tilpner** [comment]
There is a reference image in the repository: https://github.com/niofis/raybench/blob/master/crb_5000_10.png

Though it appears the back "wall" is farther back than it should be.

**Comment by tilpner** [comment]
For reference, here's how it's supposed to look like according to the newer scene descriptions:
![rsrb_100000_10](https://user-images.githubusercontent.com/4322055/57196185-dc402d80-6f49-11e9-858d-3b38ee304604.png)

**Comment by lostmsu** [comment]
Hm, I cloned just a couple of days ago, and even the C implementation produces noisy image like mine.
IMO, you should add it to the readme though.

**Comment by tilpner** [comment]
Oh, yes, the default of 50 samples is way too little for a noise-free image, and this one took 2 hours to converge. @niofis can add it to the readme if he wants.
