### ISSUE TITLE
sRGB transformation?

### ISSUE THREAD

**Issue by tilpner** [niofis/raybench#23]
Currently the output is in linear RGB, which looks very dark, and needs to be manually converted to sRGB:

```
magick rsrb_200000_20_rgb.ppm -set colorspace RGB -colorspace sRGB rsrb_200000_20_srgb.png
```

The example image should definitely be in sRGB, but perhaps each implementation should just directly produce sRGB PPMs?

See [here](https://www.nayuki.io/page/srgb-transform-library) for sRGB transformation implemented in multiple languages.

Compare the current example image to an sRGB-transformed rendering:

![linear RGB](https://raw.githubusercontent.com/niofis/raybench/master/crb_5000_10.png)
![sRGB, rsrb_200000_20](https://user-images.githubusercontent.com/4322055/57256841-44c10480-7047-11e9-8e7a-7bd7623d7daa.png)

**Comment by niofis** [comment]
This might be interesting to implement, the sRGB image looks much better. Still, the algorithm's light transport function is not correct, so there is another point of improvement there.
