### ISSUE TITLE
Functional rust implementation bug?

### ISSUE THREAD

**Issue by Avi-D-coder** [niofis/raybench#25]
Since `y` is `f32` it will have decimal values. The other implementations I have look at don't produce decimal y coordinates.

https://github.com/niofis/raybench/blob/12d79ecdfb38a878e70312940147512ba8d6c57b/rsrb_alt.rs#L286

**Comment by tilpner** [comment]
That `y` is of type `usize`, not `f32`.

**Comment by Avi-D-coder** [comment]
My bad Sourcegraph says `f32`
