### ISSUE TITLE
Consider using .NET Core?

### ISSUE THREAD

**Issue by jgowdy** [niofis/raybench#9]
You might consider trying the C# sample with [.NET Core](https://github.com/dotnet/core) rather than Mono.  Going forward C# on Linux is generally going to be about .NET Core.

Cool project! :)

**Comment by niofis** [comment]
Yeah, I expect much better performance, will try testing that soon. Thank you!

**Comment by kornakar** [comment]
You could also use the [System.Runtime.Intrinsics](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics?view=dotnet-plat-ext-2.1) namespace in the .NET Core for faster math operations.

**Comment by benaadams** [comment]
> You could also use the System.Runtime.Intrinsics namespace in the .NET Core for faster math operations.

Would be for .NET Core 3.0 (which is in preview, but not released yet); also as I understand the repo that should be a different version to distinguish it e.g. `csrb.cs` vs `csrb_vec.cs`
